### ISSUE TITLE
Content view not working in table action

### ISSUE THREAD

**Issue by CaioLevanto** [torgodly/Html2Media#2]
Following the instructions in the documentation, I tried to create a simple view

```
<div class="text-lg font-bold text-black">
    <h2>Sale No.</h2>
</div>
```

And it didn't work, and when I tried to pass 'record' it didn't work either... This happens in Tables\Actions\Html2MediaAction, do you have any recommendations on what can be done? The current code is below:

```
Html2MediaAction::make('print')
      ->content(
          fn ($record) => view('invoice')
      )
```

**Comment by CaioLevanto** [comment]
https://github.com/user-attachments/assets/3309aa0a-6f5a-457a-8ab3-2c061c4b735b

My project is already underway, I put it in and did exactly the same as the demonstration, I can send you what is generated in DevTools but no error or warning is displayed.

![image](https://github.com/user-attachments/assets/8da9f2ef-bcee-401c-bd21-18ed7cc014f7)

**Comment by CaioLevanto** [comment]
@torgodly  I discovered the problem! When "darkmode" is active and in dark mode, the letters and other information do not work... I still haven't found a way to solve the "problem" itself, but I believe this is a point to be observed!

**Comment by CaioLevanto** [comment]
Sure, I can test it! I will run it and review it, as I advised about darkmode, I took the opportunity and opened a new issue so as not to fall into limbo, I will test it in other browsers and see if the problem persists.

**Comment by torgodly** [comment]
> I discovered the problem! When "darkmode" is active and in dark mode, the letters and other information do not work... I still haven't found a way to solve the "problem" itself, but I believe this is a point to be observed!

Thanks so much for catching that! It looks like dark mode styles are indeed causing the issue with rendering. I’ve found a solution and will be working on a patch to fix this as soon as possible. Really appreciate your patience and for bringing this to my attention!
